server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/auth/**, /api/users/**, /api/freelancers/**, /api/clients/**

        - id: project-service
          uri: http://project-service:8082
          predicates:
            - Path=/api/projects/**, /api/applications/**, /api/contracts/**, /api/ratings/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: "*"